image: maven:latest

test:
  stage: test
  script:
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

checkstyle:
  stage: checkstyle
  script:
    - mvn checkstyle:checkstyle
  artifacts:
    when: always
    reports:
      -target/checkstyle-result.xml
