package de.uol.snakeinc.gui.items;

public enum RiskType {

    GLOBAL,
    SECTION,
    DEADEND,
    KILLALGORITHM,
    OPPONENTMOVERISK,
    DEADENDFLOODING,
    DEADENDFLOODING_FLOODED_CELLS,
    PATHHIGHLIGHT,
    DEADENDJUMPING

}
